### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by MaticSulc** [createit-ru/FileMan#1]
Fresh install on MODX 3.0.4 throws:

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at FileAttach.grid.Items.uploadFiles (items.grid.js?mv=304pl:445:24)
    at S.onClick (ext-all.js:21:407804)
    at HTMLSpanElement.A (ext-all.js:21:52931)
```

Enviroment is a MODX Cloud instance.

**Comment by createit-ru** [comment]
Hello. What version of FileMan do you have installed?

**Comment by MaticSulc** [comment]
@createit-ru just got latest from `modstore.pro` - 3.0.2-pl.

**Comment by createit-ru** [comment]
@MaticSulc 
In the text of the above error, I see a mention of "FileAttach".
There is no such text in the FileMan source code. You probably have the FileAttach component installed on your site and either it causes an error, or these 2 components conflict because they perform the same functions.

**Comment by MaticSulc** [comment]
@createit-ru sorry for the late response. I did have FileAttach partially installed - I tried to install it, however the installation failed.  This probably lead to some code being left, which caused this.
