### ISSUE TITLE
toPlaceholder property is set to combo-boolean, but expects the placeholder name

### ISSUE THREAD

**Issue by MaticSulc** [createit-ru/FileMan#3]
According to https://github.com/createit-ru/FileMan/blob/13eed911dc7258d4fe02d6c9be5f7520d42efcaf/_build/elements/snippets.php#L37 
the type defined in the property set for the `toPlaceholder` property is `combo-boolean`.

Inside the snippet, the name is referenced while setting the placeholder.
https://github.com/createit-ru/FileMan/blob/13eed911dc7258d4fe02d6c9be5f7520d42efcaf/core/components/fileman/elements/snippets/files.php#L94

Expected behaviour: have a separate propety for the placeholder name, or change the type of the property to `textfield`.

**Comment by createit-ru** [comment]
Hi! Thanks for the pull request and the issue. I'll look at them a little later.

**Comment by createit-ru** [comment]
Fixed in 3.15-pl
