### ISSUE TITLE
MODx log error: PHP warning: Undefined variable $range

### ISSUE THREAD

**Issue by lapp** [createit-ru/FileMan#7]
Hi,

I have the following issue in MODx error log on PHP 8.2 and MODx 3.0.5:

`
ERROR | /home/www/../core/components/fileman/src/FileMan.php | 192
PHP warning: Undefined variable $range
`

Could you check it please, thank you, Michal

**Comment by createit-ru** [comment]
fixed in 3.2.1-pl
